### ISSUE TITLE
Allow overriding default schema in `from` and `rpc`

### ISSUE THREAD

**Issue by osaxma** [supabase/supabase-flutter#206]
### **Is your feature request related to a problem? Please describe.**

Currently it's only possible to use a single schema -- i.e. the one passed to `SupabaseClient` upon instantiation. 

### **Describe the solution you'd like**

In some cases, I would like to run a query or invoke an rpc on a different schema than the one given to `SupabaseClient` such as:

```dart
final client = SupabaseClient('url', 'api_key', schema: 'public');

// some where else in the app
final res = await client.from('table_name', schema: 'api').select().eq('para', para).execute(); 
// or
final res = await client.rpc('some_function', schema: 'api_functions').select().execute();
```

In the above example, `schema` should be nullable and if it was not passed then the `SupabaseClient.schema` is used. 

### **Describe alternatives you've considered**
Creating another `SupabaseClient` seems like the only option but it'd be much easier and cleaner to use the same client. 

### Tasks
If you agree with the proposed changes, please let me know and I can carry the following tasks:

- [ ] update `rpc` method on postgrest-dart package
- [ ] update `from` method, `rpc` method, and postgrest-dart version on supabase-dart package
- [ ] update supabase-dart version on supabase-flutter package

**Comment by osaxma** [comment]
I believe it'd also be beneficial to add the options to other schema based functions such as `stream` and `on` -- not sure if I missed any others.

**Comment by dshukertjr** [comment]
Hi @osaxma,

Thanks for opening this issue! I really like your approach. I think it benefits the supabase-js client library as well to have this feature, so would you mind opening an issue on [postgrest-js](https://github.com/supabase/postgrest-js/issues) repo? If they want to implement this feature, let's go through with it on Dart side as well!

**Comment by osaxma** [comment]
Hi @dshukertjr 
Sounds good thank you. 

Here's the feature request: https://github.com/supabase/postgrest-js/issues/318

**Comment by dshukertjr** [comment]
The discussion on postgrest-js has been moved here
https://github.com/supabase/postgrest-js/issues/280

**Comment by bdotsamir** [comment]
Hi all, I've just created a PR over at postgrest-js that handles this case: https://github.com/supabase/postgrest-js/pull/441

**Comment by rddewan** [comment]
@dshukertjr is this available in flutter already ?

**Comment by dshukertjr** [comment]
@rddewan Not yet.

**Comment by Vinzent03** [comment]
This feature is now available via `client.schema("mySchema").from("myTable")`
https://github.com/supabase/supabase-flutter/blob/main/CHANGELOG.md#postgrest---v150
